### ISSUE TITLE
Receiving cURL error at random times

### ISSUE THREAD

**Issue by iamroi** [stevenmaguire/trello-php#13] opened 2016-08-25 04:04 UTC
When I try to request the below, I receive error **cURL error 56: SSL read: error:00000000:lib(0):func(0):reason(0), errno 0 (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)**

`try {
            $card_info = $trello_client->getCard($short_link);
 } catch (Exception $e) {
            echo $e->getMessage(); 
 }`

Could you please help me this issue? Thanks!

**Comment by iamroi** [comment] 2016-08-25 04:30
Also when I try to request list details, I receive 400 Bad Request error

**exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `GET https://trello.com/1/lists/5718bbe7c712e4c029f8430e?key=478740f1a438cc1xxxxf3cdc123c64&token=4b2ab341d2acb62d611435870ca6d9905acxxxxxe912639668xxxxx51bda` resulted in a `400 Bad Request`**

`try {
            $list_info = $trello_client->getList($card_info->idList);
 } catch (Exception $e) { 
     echo $e->getMessage(); 
}`

Any help would be appreciated. Thanks!

**Comment by stevenmaguire** [comment] 2016-08-26 06:33
Are you still experiencing this issue? I am afraid that I do not have enough information here to debug appropriately. 

Have you checked [StackOverflow](http://stackoverflow.com/a/3876582)?

Have you verified that your key, secret, and token are correct? 

Are you certain that the list `5718bbe7c712e4c029f8430e` exists and the user associated with the secret and token have permission to access this list?

**Comment by iamroi** [comment] 2016-08-26 06:43
Hi,

Thank you so much for getting back! Yeah I spent more than 3hrs finding the solution in StackOverflow and playing around with php.ini settings but no luck.

I can confirm that all my key and tokens and list ids are correct as this issue happens at random times.

My temporary work around is to update the 'domain' config to 'http://trello.com'. Notice the change to http from https

```
$trello_client = new Stevenmaguire\Services\Trello\Client(array(
    'domain' => 'http://trello.com',
    'key' => config_item('trello_api'),
    'secret' => config_item('trello_secret'),
    'token' => $token
));
```

**Comment by stevenmaguire** [comment] 2016-08-26 07:21
When I attempt to access the resource in question, without an access key, I get 401, not 400. I think there might be an issue with your certificate chain...

**Comment by stevenmaguire** [comment] 2016-08-28 16:26
Have you had any change in behavior on your end? Is this issue still active?

**Comment by iamroi** [comment] 2016-08-29 00:12
I still have the issue when I use https://trello.com as domain and I can't seem to figure out why. Let me know if you need me to send any specific log.

**Comment by stevenmaguire** [comment] 2016-08-29 01:07
Ok. I do not think the issue is directly related to the code in this package. Many people, myself included, have used this package without incident. I believe that your issues may stem from some network related issues. If you have any new information, I am happy to reopen and re-evaluate. Until then, I am going to close the issue.

**Closed as completed by stevenmaguire** 2016-08-29 01:07 UTC
Labels: network-issue
